-- VHDL Entity Senso_lib.Senso.symbol
--
-- Created:
--          by - st177504.st177504 (pc027)
--          at - 16:45:32 11/19/25
--
-- Generated by Siemens HDL Designer(TM) 2025.2 Built on 26 May 2025 at 14:52:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

ENTITY Senso IS
-- Declarations

END Senso ;

