--
-- VHDL Architecture Senso_lib.Senso.struct
--
-- Created:
--          by - st177504.st177504 (pc027)
--          at - 17:16:23 12/03/25
--
-- Generated by Siemens HDL Designer(TM) 2025.2 Built on 26 May 2025 at 14:52:30
--
LIBRARY ieee;
USE ieee.std_logic_1164.all;
USE ieee.numeric_std.all;

LIBRARY Senso_lib;

ARCHITECTURE struct OF Senso IS

   -- Architecture declarations

   -- Internal signal declarations
   SIGNAL clk          : std_logic;
   SIGNAL clk1         : std_logic;
   SIGNAL dec_duration : std_logic;
   SIGNAL fb           : std_logic_vector(7 DOWNTO 1);
   SIGNAL q            : std_logic_vector(7 DOWNTO 0);
   SIGNAL res_duration : std_logic;
   SIGNAL res_n        : std_logic;
   SIGNAL res_n1       : std_logic;
   SIGNAL reset        : std_logic;
   SIGNAL start_timer  : std_logic;
   SIGNAL tx_n         : std_logic;


   -- Component Declarations
   COMPONENT analyzer
   PORT (
      clk   : IN     std_logic;
      q     : IN     std_logic_vector (7 DOWNTO 0);
      res_n : IN     std_logic;
      reset : IN     std_logic
   );
   END COMPONENT;
   COMPONENT button
   PORT (
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      tx_n  : IN     std_logic;
      key   : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT button_tb
   PORT (
      clk   : OUT    std_logic;
      res_n : OUT    std_logic;
      tx_n  : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT galois_lfsr
   PORT (
      ckl   : IN     std_logic;
      fb    : IN     std_logic_vector (7 DOWNTO 1);
      res_n : IN     std_logic;
      reset : IN     std_logic;
      q     : OUT    std_logic_vector (7 DOWNTO 0)
   );
   END COMPONENT;
   COMPONENT tester
   GENERIC (
      MAX_CYCL_LENGTH : integer := 255
   );
   PORT (
      clk   : IN     std_logic;
      res_n : IN     std_logic;
      fb    : OUT    std_logic_vector (7 DOWNTO 1);
      reset : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT timer
   GENERIC (
      CLK_FREQ_HZ : integer := 50_000_000
   );
   PORT (
      clk           : IN     std_logic;
      dec_duration  : IN     std_logic;
      res_duration  : IN     std_logic;
      res_n         : IN     std_logic;
      start_timer   : IN     std_logic;
      timer_expired : OUT    std_logic
   );
   END COMPONENT;
   COMPONENT timer_tb
   PORT (
      clk          : OUT    std_logic;
      dec_duration : OUT    std_logic;
      res_duration : OUT    std_logic;
      res_n        : OUT    std_logic;
      start_timer  : OUT    std_logic
   );
   END COMPONENT;

   -- Optional embedded configurations
   -- pragma synthesis_off
   FOR ALL : analyzer USE ENTITY Senso_lib.analyzer;
   FOR ALL : button USE ENTITY Senso_lib.button;
   FOR ALL : button_tb USE ENTITY Senso_lib.button_tb;
   FOR ALL : galois_lfsr USE ENTITY Senso_lib.galois_lfsr;
   FOR ALL : tester USE ENTITY Senso_lib.tester;
   FOR ALL : timer USE ENTITY Senso_lib.timer;
   FOR ALL : timer_tb USE ENTITY Senso_lib.timer_tb;
   -- pragma synthesis_on


BEGIN

   -- Instance port mappings.
   U_6 : analyzer
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         reset => reset,
         q     => q
      );
   U_3 : button
      PORT MAP (
         clk   => clk1,
         res_n => res_n1,
         tx_n  => tx_n,
         key   => OPEN
      );
   U_2 : button_tb
      PORT MAP (
         clk   => clk1,
         res_n => res_n1,
         tx_n  => tx_n
      );
   U_5 : galois_lfsr
      PORT MAP (
         ckl   => clk,
         res_n => res_n,
         reset => reset,
         fb    => fb,
         q     => q
      );
   U_4 : tester
      GENERIC MAP (
         MAX_CYCL_LENGTH => 255
      )
      PORT MAP (
         clk   => clk,
         res_n => res_n,
         reset => reset,
         fb    => fb
      );
   U_0 : timer
      GENERIC MAP (
         CLK_FREQ_HZ => 50_000_000
      )
      PORT MAP (
         clk           => clk,
         res_n         => res_n,
         start_timer   => start_timer,
         dec_duration  => dec_duration,
         res_duration  => res_duration,
         timer_expired => OPEN
      );
   U_1 : timer_tb
      PORT MAP (
         clk          => clk,
         res_n        => res_n,
         start_timer  => start_timer,
         dec_duration => dec_duration,
         res_duration => res_duration
      );

END struct;
